Reorganize hyperparameters and init hierarchical nonstationary hyperparameter
LLNL/MuyGPyS pull request #129
Opened 2023-04-13 06:20 UTC by igoumiri

Since I was about to introduce a third type of hyperparameter, I moved them all to a new directory and I renamed `Hyperparameter` to `ScalarHyperparameter`. I added a stub of `HierarchicalNonstationaryHyperparameter` based on https://github.com/LLNL/MuyGPyS/issues/71 and I figured I'd rather do incremental small PRs so I'm putting this one out.

Some of the files got auto-formatted since I run black on save.

2023-04-13 06:34 UTC, igoumiri commented
Hmm, there is a circular dependency because the hierarchical hyperparameter needs a kernel… Maybe it should receive the kernel itself in `__init__` rather than the `kwargs`?

2023-04-13 17:41 UTC, bwpriest requested changes
A lot of the changes that you made make sense. The challenges that I am seeing here are as follows:
1. The backend tests are failing due to a circular import relating to `embed_with_distortion_model`.
2. The tests need to be updated to use `ScalarHyperparameter`.
3. We need some preliminary tests that validate the expected behavior of `HierarchicalNonstationaryHyperparameter`.
4. I think that we should move `HierarchicalNonstationaryHyperparameter` into `MuyGPyS.gp.hyperparameter.experimental`, as it will likely be only partially functional for a while and we don't want to give the impression that it is finished.

2023-04-13 17:41 UTC, bwpriest commented on MuyGPyS/gp/hyperparameter/hierarchical_nonstationary.py
> +        self.kernel = RBF(**k_kwargs)
We will probably want to revisit this interface before we decide on the final API

2023-04-13 17:41 UTC, bwpriest commented on MuyGPyS/gp/hyperparameter/hierarchical_nonstationary.py
> +        lower_K = self.kernel(mm._pairwise_distances(self.knot_features))
`mm._pairwise_distances` does not exist. `MuyGPyS.gp.tensors.pairwise_tensors` is built for MuyGPs nearest neighbors tensor math, so that is not suitable for our current purposes, but I think that we can use `_pairwise_diffs` (defined in `MuyGPyS._src`) for this purpose. The same story is true for `mm._crosswise_distances` and `_crosswise_diffs`. However, that function is not currently exposed to the program. We'll need to add it to `MuyGPyS/_src/gp/tensors/__init__.py`. That will require modifying the `_collect_implementation` call therein to
```
(
    _make_predict_tensors,
    _make_fast_predict_tensors,
    _make_train_tensors,
    _crosswise_diffs,           # <-- new
    _crosswise_tensor,
    _pairwise_diffs,            # <-- new
    _pairwise_tensor,
    _fast_nn_update,
    _make_heteroscedastic_tensor,
    _F2,
    _l2,
) = _collect_implementation(
    "MuyGPyS._src.gp.tensors",
    "_make_predict_tensors",
    "_make_fast_predict_tensors",
    "_make_train_tensors",
    "_crosswise_diffs",              # <-- new
    "_crosswise_tensor",
    "_pairwise_diffs",               # <-- new
    "_pairwise_tensor",
    "_fast_nn_update",
    "_make_heteroscedastic_tensor",
    "_F2",
    "_l2",
```

2023-04-13 17:41 UTC, bwpriest commented on MuyGPyS/gp/hyperparameter/hierarchical_nonstationary.py
> +            mm._crosswise_distances(batch_features, self.knot_features)
Here is the `crosswise_distances` call that needs to be replaced.

2023-04-13 17:41 UTC, bwpriest commented on MuyGPyS/gp/hyperparameter/hierarchical_nonstationary.py
> +        return lower_Kcross @ self.solve
This currently allows the user to get many hyperparameter values for a corresponding number of locations at once. I think that makes sense computationally, but we'll need to be careful about how we write the codes that use this class.

2023-04-13 17:55 UTC, bwpriest commented
> Some of the files got auto-formatted since I run black on save.

I think that you need to add the arguments `--line-length 80` to your `black` invocations so that all of our autoformats agree. If you are using vscode, you need to add the lines `--line-length` and `80` to `Python › Formatting: Black Args` in your settings. If you are using a different solution or you need help, please let me know.

2023-04-15 20:58 UTC, igoumiri commented on .github/workflows/develop-test.yml
> -          pytyon tests/batch.py
Oops! Looks like the tests are executing properly.

2023-04-15 20:59 UTC, igoumiri commented on setup.py
> +    "pandoc==2.3.0",
I ran into an issue that got fixed in https://github.com/boisgera/pandoc/pull/49

2023-04-18 02:04 UTC, bwpriest commented on .github/workflows/develop-test.yml
> -          pytyon tests/batch.py
I've fixed this in another PR

2023-04-18 02:05 UTC, bwpriest commented on setup.py
> +    "pandoc==2.3.0",
Thanks for the fix!

2023-04-18 02:22 UTC, bwpriest approved these changes
LGTM.

2023-04-18 02:24 UTC, bwpriest commented on MuyGPyS/_src/gp/tensors/mpi.py
> +    )
We'll need to correct this similar to `_crosswise_tensors`, but that will be easy to do in a subsequent PR.

2023-04-18 02:24 UTC, bwpriest commented on MuyGPyS/_src/gp/tensors/mpi.py
> +    )
Same story here.

2023-04-18 02:25 UTC, merged