Feature: hierarchical RBF
LLNL/MuyGPyS pull request #145
Opened 2023-04-27 15:53 UTC by igoumiri

This is work in progress to do what's described in https://github.com/LLNL/MuyGPyS/issues/71

2023-04-27 20:47 UTC, bwpriest requested changes
I think that we need to discuss how to achieve what you are attempting with your modifications to `_rbf_fn`.

2023-04-27 20:47 UTC, bwpriest commented on MuyGPyS/_src/gp/kernels/numpy.py
Those comments in #71 are very out of date. We need `_rbf_fn` to retain the signature that it currently has in develop, as `length_scale` has moved outside of the kernel functions entirely. What you are doing here looks like it can be accomplished with `AnisotropicDistortion`.

2023-04-27 20:47 UTC, bwpriest commented on MuyGPyS/_src/gp/tensors/__init__.py
I don't like the name `_make_batch_tensor`, as there are several different types of "batch tensors". I think it would be better to call this `_batch_features_tensor` or similar

2023-04-27 20:47 UTC, bwpriest commented on MuyGPyS/gp/distortion/anisotropic.py
> +        ],
I don't think that we should pollute typehints with experimental features before the features are stable.

2023-04-27 20:47 UTC, bwpriest commented on MuyGPyS/gp/distortion/embed.py
> +    ):
`HierarchicalNonstationaryHyperparameter` should have its own conditional block, even if it does the same thing as `ScalarHyperparameter`.

2023-04-27 20:47 UTC, bwpriest commented on MuyGPyS/gp/distortion/embed.py
> +    ):
In the future we might add logging, warnings, or change the behavior so we should keep them separated.

2023-04-27 20:47 UTC, bwpriest commented on MuyGPyS/gp/distortion/anisotropic.py
> +        ],
Let me know if you're doing this to make `mypy` behave or something

2023-04-27 20:47 UTC, bwpriest commented on MuyGPyS/gp/kernels/rbf.py
> +        )
This is not how we want to handle this, as the way that we handle kernel functions has changed over the last two months. We should talk about what you are trying to do here.

2023-04-27 20:47 UTC, bwpriest commented on MuyGPyS/gp/tensors.py
> +) -> mm.ndarray:
We should update the api function to a matching name, like `batch_features_tensor`.

2023-04-27 21:23 UTC, bwpriest commented on MuyGPyS/gp/distortion/embed.py
> +    ):
We also want to keep the experimental control flow as segregated as possible from the stable stuff.

2023-04-27 21:24 UTC, bwpriest commented on MuyGPyS/gp/kernels/rbf.py
> +        )
I made some comments on issue #71 that address this

2023-04-27 21:24 UTC, bwpriest commented on MuyGPyS/_src/gp/kernels/numpy.py
I made some new comments in #71 that address this.

2023-04-28 02:45 UTC, bwpriest commented on MuyGPyS/_src/gp/kernels/numpy.py
You're right. Anisotropic does not come into this at all. I think my comment on #71 spells out what we're should be doing instead, although it will probably get a little more complicated when we need to optimize.

2023-05-02 21:30 UTC, bwpriest requested changes
Looks like we're making progress. I suggest creating separate test class(es) entirely for the Hierarchical parameters, since they behave a little differently than the others. Do you have any example notebooks that illustrate the behavior of the hierarchical parameters?

2023-05-03 05:15 UTC, igoumiri commented on tests/gp.py
> +            ),
Yes, I was going to add more specific tests but I also agree that removing this one is better.

2023-05-03 05:19 UTC, igoumiri commented
> Do you have any example notebooks that illustrate the behavior of the hierarchical parameters?

I was initially thinking of baking it in `do_regress` and maybe other places from `examples` but a notebook seems like a good idea. Didn't you mention something about deprecating `do_regress` anyway?

2023-05-03 17:16 UTC, bwpriest commented
> I was initially thinking of baking it in `do_regress` and maybe other places from `examples` but a notebook seems like a good idea. Didn't you mention something about deprecating `do_regress` anyway?

Yes, we are going to massively simplify `MuyGPyS.examples` for the 1.0 release. In the future, all of the scripts in `MuyGPyS.examples` will be made into very simple, single-use scripts. Each script will target a single backend as well. Their primary purpose will be to be read. It will be possible to use them, but that will be primarily for educational purposes.

I'd really like you to add a notebook to `docs/examples`. It can be simple. A runnable notebook will give us an easy way to play with the feature and make sure that it works as we are developing it, and the notebook itself will serve as documentation.

2023-05-04 06:57 UTC, igoumiri commented
I'm still working on:
1. adding more tests, in particular testing with anisotropic distortion
2. the notebook

2023-05-04 06:58 UTC, igoumiri commented on MuyGPyS/gp/distortion/isotropic.py
> +        length_scale = mm.array(length_scale).reshape(shape)
I might put this in a `_get_length_scale_array` like in anisotropic

2023-05-09 06:50 UTC, igoumiri commented
I created a notebook. You can preview it here: https://github.com/LLNL/MuyGPyS/blob/753d7122e55b2662565348be477ab41828f937ef/docs/examples/nonstationary_tutorial.ipynb

It's a starting point. Right now it mostly shows that it runs and how to pass the extra argument to the kernel.

The failing tests are just due to randomness. I suppose we could keep increasing the thresholds, or maybe there is a way to provide initial guesses close to the expected values?

2023-05-09 06:57 UTC, igoumiri commented on MuyGPyS/gp/distortion/anisotropic.py
> +        ).T
This reshape/concat/transpose is not my favorite but it works and I couldn't find a better way

2023-05-09 16:57 UTC, bwpriest commented on docs/examples/nonstationary_tutorial.ipynb
When committing a notebook, it is necessary to select `Kernel > Restart and Clear All Outputs` and save, so that we only track the markdown/code in cells and no outputs. There are a few reasons for this. First, it saves on repo size since we aren't storing plot images and the like. Second, it is required for the `sphinx` extensions that we are using to build these notebooks into doc webpages on readthedocs (RTD). RTD gets sad and barfs if the notebooks have state.

2023-05-09 18:04 UTC, igoumiri commented on MuyGPyS/gp/distortion/anisotropic.py
> +        ).T
> I think that you also need to accept and pass batch_features to the optional invocation of hyperparameter functors a few lines above this, or else it will barf when you use it with HierarchicalNonstationaryHyperparameter.

Do you mean in `__call__` and the call to `self._dist_fn()`? I think we already did in RBF's `__call__` and so `_dist_fn` should already have the batch_features, no?

2023-05-09 23:10 UTC, bwpriest commented on MuyGPyS/gp/distortion/anisotropic.py
> +        ).T
I think that you fixed this. We'll want tests that cover all of this behavior though.

2023-05-09 23:59 UTC, bwpriest approved these changes
LGTM

2023-05-10 00:00 UTC, merged